import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import { ArrowIcon } from '../arrow-icon';

type Props = {
  title: string;
  isLoading?: boolean;
  children?: React.ReactNode;
};

export const BasePage: React.FC<Props> = ({
  title,
  children,
  isLoading = false,
}) => {
  const { pathname } = useRouter();

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-8">
          {pathname !== '/' && (
            <Link
              href="/"
              className="w-15 h-15 absolute top-10 left-10 flex cursor-pointer rounded-full border-2 border-gray-500 p-5 transition duration-300 hover:bg-violet-900 active:bg-violet-800"
            >
              <ArrowIcon />
            </Link>
          )}
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            {title}
          </h1>

          <div>{isLoading ? <p>Loading..</p> : children}</div>
        </div>
      </main>
    </>
  );
};
