import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import { ArrowIcon } from '@components';

type Props = {
  title: string;
  children?: React.ReactNode;
};
export const BasePage: React.FC<Props> = ({ title, children }) => {
  const { pathname } = useRouter();

  console.log('pathname', pathname);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-8">
          {pathname !== '/' && (
            <Link
              href="/"
              className="absolute top-10 left-10 w-15 h-15 p-5 flex border-2 border-gray-500 rounded-full cursor-pointer hover:bg-violet-900 active:bg-violet-800 transition duration-300"
            >
              <ArrowIcon />
            </Link>
          )}

          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            {title}
          </h1>

          {children}
        </div>
      </main>
    </>
  );
};
